# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e34dff0c8fe355ea1b5e69288e666fdc8a6c940a3fcae84a1bfe6b7bd508d2b7da1295130c315af14bebccd28ef6a4ea0c47319f714ef09625130fe9148ec54

test:
  secret_key_base: c8d7d73feaa906bdb0a9a1913c881165a543f69e5b629333edf63e4b5684bfb4fedd07d2c5ac39063bf7464a877851ab15b4fe285826a5bb2ea1294d7287716d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
